<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<artifactId>clinic-webapp0</artifactId>
	<packaging>jar</packaging>
	<parent>
		<groupId>edu.stevens.cs548</groupId>
		<artifactId>clinic-root</artifactId>
		<version>1.0.0</version>
		<relativePath>../clinic-root/pom.xml</relativePath>
	</parent>

	<properties>
		<app.name>clinic-webapp</app.name>
	</properties>

	<build>
		<plugins>
            <plugin>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
            </plugin>
		</plugins>
	</build>
	<dependencies>
        <dependency>
            <groupId>io.quarkiverse.qute.web</groupId>
            <artifactId>quarkus-qute-web</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-container-image-docker</artifactId>
        </dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-junit5</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>edu.stevens.cs548</groupId>
			<artifactId>clinic-init0</artifactId>
		</dependency>
	</dependencies>
</project>
