<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>edu.stevens.cs548</groupId>
    <artifactId>clinic-root</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>clinic-root</name>
    <url>http://maven.apache.org</url>

    <modules>

        <module>../clinic-dto</module>
        <module>../clinic-domain</module>
        <module>../clinic-service-client</module>
        <module>../clinic-service</module>
        <module>../clinic-init</module>
        <module>../clinic-webapp</module>
        <module>../clinic-rest</module>
        <module>../clinic-rest-client</module>

    </modules>

    <properties>
        <compiler-plugin.version>3.14.0</compiler-plugin.version>
        <maven.compiler.release>21</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
        <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
        <quarkus.platform.version>3.27.2</quarkus.platform.version>
        <skipITs>true</skipITs>
        <surefire-plugin.version>3.5.3</surefire-plugin.version>

        <!-- https://quarkus.io/guides/maven-tooling#build-tool-maven -->
        <skipITs>true</skipITs>

        <dist.dir>${user.home}/tmp/cs548</dist.dir>

    </properties>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>${quarkus.platform.group-id}</groupId>
                    <artifactId>quarkus-maven-plugin</artifactId>
                    <version>${quarkus.platform.version}</version>
                    <extensions>true</extensions>
                    <executions>
                        <execution>
                            <goals>
                                <goal>build</goal>
                                <goal>generate-code</goal>
                                <goal>generate-code-tests</goal>
                                <goal>native-image-agent</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>

                <plugin>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${compiler-plugin.version}</version>
                    <configuration>
                        <parameters>true</parameters>
                    </configuration>
                </plugin>

                <plugin>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${surefire-plugin.version}</version>
                    <configuration>
                        <systemPropertyVariables>
                            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                            <maven.home>${maven.home}</maven.home>
                        </systemPropertyVariables>
                    </configuration>
                </plugin>
                <plugin>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <version>${surefire-plugin.version}</version>
                    <executions>
                        <execution>
                            <goals>
                                <goal>integration-test</goal>
                                <goal>verify</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <systemPropertyVariables>
                            <native.image.path>${project.build.directory}/${project.build.finalName}-runner
                            </native.image.path>
                            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                            <maven.home>${maven.home}</maven.home>
                        </systemPropertyVariables>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-antrun-plugin</artifactId>
                    <version>3.1.0</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-assembly-plugin</artifactId>
                    <version>3.6.0</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>${quarkus.platform.artifact-id}</artifactId>
                <version>${quarkus.platform.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.eclipse.microprofile</groupId>
                <artifactId>microprofile</artifactId>
                <version>6.0</version>
                <type>pom</type>
                <scope>provided</scope>
            </dependency>

            <!-- UUID v7 -->
            <dependency>
                <groupId>com.fasterxml.uuid</groupId>
                <artifactId>java-uuid-generator</artifactId>
                <version>5.1.0</version>
            </dependency>

            <!-- https://mvnrepository.com/artifact/com.squareup.retrofit2/retrofit -->
            <dependency>
                <groupId>com.squareup.retrofit2</groupId>
                <artifactId>retrofit</artifactId>
                <version>2.12.0</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/com.squareup.retrofit2/converter-gson -->
            <dependency>
                <groupId>com.squareup.retrofit2</groupId>
                <artifactId>converter-jackson</artifactId>
                <version>2.12.0</version>
            </dependency>

            <!-- Jackson data binding -->
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-core</artifactId>
                <version>2.20.0</version> <!-- Use the latest stable version -->
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>2.20.0</version> <!-- Use the latest stable version -->
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-annotations</artifactId>
                <version>2.20</version> <!-- Use the latest stable version -->
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.datatype</groupId>
                <artifactId>jackson-datatype-jsr310</artifactId>
                <version>2.20.0</version>
            </dependency>
            <dependency>
                <groupId>com.sigpwned</groupId>
                <artifactId>jackson-modules-java17-sealed-classes</artifactId>
                <version>2.19.0.0</version>
            </dependency>

            <dependency>
                <groupId>junit</groupId>
                <artifactId>junit</artifactId>
                <version>3.8.1</version>
                <scope>test</scope>
            </dependency>

            <!-- Intra-app dependencies. -->
            <dependency>
                <groupId>edu.stevens.cs548</groupId>
                <artifactId>clinic-dto</artifactId>
                <version>1.0.0</version>
            </dependency>

            <dependency>
                <groupId>edu.stevens.cs548</groupId>
                <artifactId>clinic-domain</artifactId>
                <version>1.0.0</version>
            </dependency>

            <dependency>
                <groupId>edu.stevens.cs548</groupId>
                <artifactId>clinic-init</artifactId>
                <version>1.0.0</version>
            </dependency>

            <dependency>
                <groupId>edu.stevens.cs548</groupId>
                <artifactId>clinic-service-client</artifactId>
                <version>1.0.0</version>
            </dependency>

            <dependency>
                <groupId>edu.stevens.cs548</groupId>
                <artifactId>clinic-service</artifactId>
                <version>1.0.0</version>
            </dependency>

            <dependency>
                <groupId>edu.stevens.cs548</groupId>
                <artifactId>clinic-rest</artifactId>
                <version>1.0.0</version>
                <type>war</type>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <profiles>
        <profile>
            <id>native</id>
            <properties>
                <quarkus.native.enabled>true</quarkus.native.enabled>
                <skipITs>false</skipITs>
            </properties>
        </profile>
    </profiles>

</project>
