#
# These are the same as the defaults.
#
quarkus.index-dependency.acme.group-id=edu.stevens.cs548
quarkus.package.jar.type=fast-jar
quarkus.http.port=8080
#
# Container image build
#
quarkus.container-image.build=true
quarkus.container-image.group=cs548
quarkus.container-image.name=clinic-webapp

#
# Database Configuration
#
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=clinicuser
quarkus.datasource.password=clinic456
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/clinic

#
# Hibernate Configuration
#
quarkus.hibernate-orm.database.generation=drop-and-create
