#
# https://thorben-janssen.com/hibernate-logging-guide/
#
# Logger properties
#
handlers=java.util.logging.FileHandler
java.util.logging.FileHandler.level=FINEST
java.util.logging.FileHandler.pattern=database.log
java.util.logging.FileHandler.formatter=java.util.logging.SimpleFormatter
#
# Hibernate
#
# basic log level for all messages
org.hibernate.SQL.level=FINER
org.hibernate.orm.jdbc.bind.level=FINEST
# Statistics
org.hibernate.stat.level=FINER
org.hibernate.SQL_SLOW.level=INFO
# 2nd Level Cache
org.hibernate.cache.level=FINER
